
import { Inter } from 'next/font/google'
import './tailwinGlobal.scss'
import StyledComponentRegistry from './lib/registry'
import { Roboto } from 'next/font/google'

const roboto = Roboto({
  weight:['400','700'],
  style:['normal','italic'],
  subsets:['latin'],
  variable:'--font-roboto',
  display:'swap'
})

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head lang='esp' className={roboto.className} />
      <body className={inter.className}>
        <StyledComponentRegistry>
               {children}
        </StyledComponentRegistry>
      </body>
    </html>
  )
}
